export type ReciprocalClub = {
  name: string;
  country: string;
  address: string;
  website: string;
  email?: string;
  phone: string;
};

export const COUNTRIES = [
  "India",
  "United Kingdom",
  "Kenya",
  "Singapore",
  "Thailand",
  "Australia",
  "Malaysia",
] as const;

export const RECIPROCAL_CLUBS: ReciprocalClub[] = [
  {
    name: "Bangalore Club",
    country: "India",
    address: "Field Marshal K.M. Cariappa Road, Bangalore",
    website: "www.bangaloreclub.com",
    email: "secretary@bangaloreclub.com",
    phone: "+91 80660 60000",
  },
  {
    name: "Belgaum Presidency Club",
    country: "India",
    address: "CTS 1019, Near BUDA Office, Ashok Nagar, Shivaji Nagar, Belagavi, Karnataka",
    website: "www.belgaumpresidencyclub.com",
    email: "info@belgaumpresidency.club",
    phone: "+91 6366356971",
  },
  {
    name: "Belvedere Golf & Country Club Pvt. Ltd.",
    country: "India",
    address: "S.G. Highway, Near Vaishnodevi Circle, Adani Shantigram CBD, Ahmedabad",
    website: "ahmedabad.belvedereclub.in",
    email: "info.ahd@belvedereclub.in",
    phone: "+91 79 6651 5151",
  },
  {
    name: "City University Club",
    country: "United Kingdom",
    address: "42 Crutched Friars, London EC3N 2AP, United Kingdom",
    website: "www.cityuniversityclub.co.uk",
    email: "secretary@cityuniversityclub.co.uk",
    phone: "020 7863 6681",
  },
  {
    name: "Deccan Gymkhana",
    country: "India",
    address: "Survey No. 759/1, Ground Floor, Club House Building, Deccan Gymkhana, Pune",
    website: "deccangymkhana.co.in",
    email: "info@deccangymkhana.org",
    phone: "020 2567 5994",
  },
  {
    name: "Delhi Gymkhana Club",
    country: "India",
    address: "2, Safdarjung Road, New Delhi – 110011",
    website: "delhigymkhana.org.in",
    email: "support@delhigymkhana.org.in",
    phone: "011-23015531 – 35, 011-23012773",
  },
  {
    name: "Emerald Garden Club",
    country: "India",
    address: "Off Ajmer Road (Bhakrota), Jaipur 302026",
    website: "www.emeraldgardenclub.com",
    email: "info@emeraldgardenclub.com",
    phone: "07737555509, 07737555512",
  },
  {
    name: "Golden Swan Country Club",
    country: "India",
    address: "Off Pokharan Rd Number 1, Bendipada, Yeoor Hills, Thane West, Thane",
    website: "www.goldenswan.club",
    email: "countryclub@goldenswan.com",
    phone: "+91 22 2585 6515",
  },
  {
    name: "Indian Gymkhana Club",
    country: "India",
    address: "Cox Town, Bengaluru, Karnataka 560005, India",
    website: "indiangymkhanaclub.co.uk",
    email: "contactus@igbangalore.com",
    phone: "+91 80 2548 3208",
  },
  {
    name: "Jaisal Club Ltd",
    country: "India",
    address: "Industrial Area, Gandhi Nagar, Jaisalmer, Rajasthan 345001",
    website: "www.jaisalclub.com",
    email: "info@jaisalclub.com",
    phone: "02992-255555",
  },
  {
    name: "Lodhi Club",
    country: "India",
    address: "Lodhi Club Rd, Block I, Bhai Randhir Singh Nagar, Ludhiana, Punjab",
    website: "www.lodhiclub.org",
    email: "lodhiclub.ldh@gmail.com",
    phone: "0161-2459013-14",
  },
  {
    name: "Njoro Country Club",
    country: "Kenya",
    address: "P.O. Box 250, Njoro",
    website: "www.njorocountryclub.co.ke",
    email: "info@njorocountryclub.com",
    phone: "+254 0797-710-871",
  },
  {
    name: "Oudh Gymkhana Club",
    country: "India",
    address: "Kaiserbagh, Lucknow",
    website: "ogc.org.in",
    email: "ogclko@gmail.com",
    phone: "0522-2202013",
  },
  {
    name: "Singapore Cricket Club",
    country: "Singapore",
    address: "Connaught Drive, Singapore 179681",
    website: "scc.org.sg",
    email: "scc@scc.org.sg",
    phone: "+65 6338 9271",
  },
  {
    name: "Spoorti Resort & Clubhouse",
    country: "India",
    address: "Beside Sukoon Layout, Ring Road, Vijayapur 586103",
    website: "www.spoorti.in",
    email: "info@spoorti.in",
    phone: "+91 63623 92876",
  },
  {
    name: "Suncity Club & Resort",
    country: "India",
    address: "Next to Chandan Multiplex, Gotri-Sherkhi Road, Vadodara, Gujarat",
    website: "www.suncityclub.in",
    email: "info@suncityclub.in",
    phone: "07211132201",
  },
  {
    name: "The British Club Bangkok",
    country: "Thailand",
    address: "189 Surawong Road, Bangrak, Bangkok 10500",
    website: "www.britishclubbangkok.org",
    email: "info@britishclubbangkok.org",
    phone: "+66 2234 0247",
  },
  {
    name: "The Catholic Gymkhana Limited",
    country: "India",
    address: "47-A, Near Taraporewala Aquarium, Netaji Subhash Chandra Bose Rd, Mumbai",
    website: "www.catholicgymkhana.com",
    email: "office@thecatholicgymkhana.com",
    phone: "+91 22 2281 4755",
  },
  {
    name: "The Geraldton Golf Club",
    country: "Australia",
    address: "30 Pass Street, Geraldton WA 6530",
    website: "www.geraldtongolfclub.com.au",
    email: "email@geraldtongolfclub.com.au",
    phone: "(08) 9964 1911",
  },
  {
    name: "The Wellington Gymkhana Club",
    country: "India",
    address: "Wellington Gymkhana Club, Wellington, Barracks Post, Nilgiris – 643231",
    website: "wellingtongymkhanaclub.co.in",
    email: "wgc@wellingtongymkhanaclub.co.in",
    phone: "0423 2244030-59",
  },
  {
    name: "The Willingdon Sports Club",
    country: "India",
    address: "Arya Nagar, Tulsiwadi, Tardeo, Mumbai, Maharashtra 400034",
    website: "www.willingdonclub.com",
    email: "edp@willingdonclub.com",
    phone: "+91 22 2352 8600",
  },
  {
    name: "National Sports Club of India",
    country: "India",
    address: "Mathura Road, New Delhi-110001",
    website: "www.nscidelhi.com",
    email: "info@nscidelhi.com",
    phone: "+91 8588811438",
  },
  {
    name: "Karnataka Golf Association",
    country: "India",
    address: "No. 1, Golf Avenue, Old Airport Road, Bangalore",
    website: "www.kga.in",
    email: "golf@kga.in",
    phone: "+91 80 4009 0000",
  },
  {
    name: "Gymkhana Club Goa",
    country: "India",
    address: "Duelmol, Sirvoi, Quepem, South Goa 403705",
    website: "www.deaojose.in/gymkhanalegacy",
    email: "info@deaojose.in",
    phone: "9823404242",
  },
  {
    name: "The Royal Selangor Golf Club",
    country: "Malaysia",
    address: "Jalan Kelab Golf, 55000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
    website: "rsgc.com.my",
    email: "info@rsgc.com.my",
    phone: "+60 3-9206 3333",
  },
  {
    name: "Bowring Institute",
    country: "India",
    address: "19 St Mark's Rd, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka",
    website: "bowringinstitute.in",
    phone: "+91 80 2222 8881",
  },
];
