/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenueHireRouteImport } from './routes/venue-hire'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as MembershipIndexRouteImport } from './routes/membership.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as DiningIndexRouteImport } from './routes/dining.index'
import { Route as TheClubRulesRouteImport } from './routes/the-club.rules'
import { Route as TheClubProcurementRouteImport } from './routes/the-club.procurement'
import { Route as TheClubHistoryRouteImport } from './routes/the-club.history'
import { Route as TheClubCommitteeRouteImport } from './routes/the-club.committee'
import { Route as TheClubCareersRouteImport } from './routes/the-club.careers'
import { Route as SportsZumbaRouteImport } from './routes/sports.zumba'
import { Route as SportsYogaRouteImport } from './routes/sports.yoga'
import { Route as SportsTennisRouteImport } from './routes/sports.tennis'
import { Route as SportsTaichiRouteImport } from './routes/sports.taichi'
import { Route as SportsSquashRouteImport } from './routes/sports.squash'
import { Route as SportsPoolRouteImport } from './routes/sports.pool'
import { Route as SportsPaddleRouteImport } from './routes/sports.paddle'
import { Route as SportsGolfRouteImport } from './routes/sports.golf'
import { Route as SportsFootballRouteImport } from './routes/sports.football'
import { Route as SportsFitnessRouteImport } from './routes/sports.fitness'
import { Route as SportsBollywoodRouteImport } from './routes/sports.bollywood'
import { Route as MembershipReciprocalRouteImport } from './routes/membership.reciprocal'
import { Route as GalleryAlbumRouteImport } from './routes/gallery.$album'
import { Route as BackOfficeLoginRouteImport } from './routes/back-office.login'
import { Route as DiningMenusMenuRouteImport } from './routes/dining.menus.$menu'

const VenueHireRoute = VenueHireRouteImport.update({
  id: '/venue-hire',
  path: '/venue-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/membership/',
  path: '/membership/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningIndexRoute = DiningIndexRouteImport.update({
  id: '/dining/',
  path: '/dining/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubRulesRoute = TheClubRulesRouteImport.update({
  id: '/the-club/rules',
  path: '/the-club/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubProcurementRoute = TheClubProcurementRouteImport.update({
  id: '/the-club/procurement',
  path: '/the-club/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubHistoryRoute = TheClubHistoryRouteImport.update({
  id: '/the-club/history',
  path: '/the-club/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubCommitteeRoute = TheClubCommitteeRouteImport.update({
  id: '/the-club/committee',
  path: '/the-club/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubCareersRoute = TheClubCareersRouteImport.update({
  id: '/the-club/careers',
  path: '/the-club/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsZumbaRoute = SportsZumbaRouteImport.update({
  id: '/sports/zumba',
  path: '/sports/zumba',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsYogaRoute = SportsYogaRouteImport.update({
  id: '/sports/yoga',
  path: '/sports/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsTennisRoute = SportsTennisRouteImport.update({
  id: '/sports/tennis',
  path: '/sports/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsTaichiRoute = SportsTaichiRouteImport.update({
  id: '/sports/taichi',
  path: '/sports/taichi',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSquashRoute = SportsSquashRouteImport.update({
  id: '/sports/squash',
  path: '/sports/squash',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsPoolRoute = SportsPoolRouteImport.update({
  id: '/sports/pool',
  path: '/sports/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsPaddleRoute = SportsPaddleRouteImport.update({
  id: '/sports/paddle',
  path: '/sports/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsGolfRoute = SportsGolfRouteImport.update({
  id: '/sports/golf',
  path: '/sports/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsFootballRoute = SportsFootballRouteImport.update({
  id: '/sports/football',
  path: '/sports/football',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsFitnessRoute = SportsFitnessRouteImport.update({
  id: '/sports/fitness',
  path: '/sports/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsBollywoodRoute = SportsBollywoodRouteImport.update({
  id: '/sports/bollywood',
  path: '/sports/bollywood',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipReciprocalRoute = MembershipReciprocalRouteImport.update({
  id: '/membership/reciprocal',
  path: '/membership/reciprocal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryAlbumRoute = GalleryAlbumRouteImport.update({
  id: '/gallery/$album',
  path: '/gallery/$album',
  getParentRoute: () => rootRouteImport,
} as any)
const BackOfficeLoginRoute = BackOfficeLoginRouteImport.update({
  id: '/back-office/login',
  path: '/back-office/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningMenusMenuRoute = DiningMenusMenuRouteImport.update({
  id: '/dining/menus/$menu',
  path: '/dining/menus/$menu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue-hire': typeof VenueHireRoute
  '/back-office/login': typeof BackOfficeLoginRoute
  '/gallery/$album': typeof GalleryAlbumRoute
  '/membership/reciprocal': typeof MembershipReciprocalRoute
  '/sports/bollywood': typeof SportsBollywoodRoute
  '/sports/fitness': typeof SportsFitnessRoute
  '/sports/football': typeof SportsFootballRoute
  '/sports/golf': typeof SportsGolfRoute
  '/sports/paddle': typeof SportsPaddleRoute
  '/sports/pool': typeof SportsPoolRoute
  '/sports/squash': typeof SportsSquashRoute
  '/sports/taichi': typeof SportsTaichiRoute
  '/sports/tennis': typeof SportsTennisRoute
  '/sports/yoga': typeof SportsYogaRoute
  '/sports/zumba': typeof SportsZumbaRoute
  '/the-club/careers': typeof TheClubCareersRoute
  '/the-club/committee': typeof TheClubCommitteeRoute
  '/the-club/history': typeof TheClubHistoryRoute
  '/the-club/procurement': typeof TheClubProcurementRoute
  '/the-club/rules': typeof TheClubRulesRoute
  '/dining/': typeof DiningIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/dining/menus/$menu': typeof DiningMenusMenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue-hire': typeof VenueHireRoute
  '/back-office/login': typeof BackOfficeLoginRoute
  '/gallery/$album': typeof GalleryAlbumRoute
  '/membership/reciprocal': typeof MembershipReciprocalRoute
  '/sports/bollywood': typeof SportsBollywoodRoute
  '/sports/fitness': typeof SportsFitnessRoute
  '/sports/football': typeof SportsFootballRoute
  '/sports/golf': typeof SportsGolfRoute
  '/sports/paddle': typeof SportsPaddleRoute
  '/sports/pool': typeof SportsPoolRoute
  '/sports/squash': typeof SportsSquashRoute
  '/sports/taichi': typeof SportsTaichiRoute
  '/sports/tennis': typeof SportsTennisRoute
  '/sports/yoga': typeof SportsYogaRoute
  '/sports/zumba': typeof SportsZumbaRoute
  '/the-club/careers': typeof TheClubCareersRoute
  '/the-club/committee': typeof TheClubCommitteeRoute
  '/the-club/history': typeof TheClubHistoryRoute
  '/the-club/procurement': typeof TheClubProcurementRoute
  '/the-club/rules': typeof TheClubRulesRoute
  '/dining': typeof DiningIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/membership': typeof MembershipIndexRoute
  '/sports': typeof SportsIndexRoute
  '/dining/menus/$menu': typeof DiningMenusMenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue-hire': typeof VenueHireRoute
  '/back-office/login': typeof BackOfficeLoginRoute
  '/gallery/$album': typeof GalleryAlbumRoute
  '/membership/reciprocal': typeof MembershipReciprocalRoute
  '/sports/bollywood': typeof SportsBollywoodRoute
  '/sports/fitness': typeof SportsFitnessRoute
  '/sports/football': typeof SportsFootballRoute
  '/sports/golf': typeof SportsGolfRoute
  '/sports/paddle': typeof SportsPaddleRoute
  '/sports/pool': typeof SportsPoolRoute
  '/sports/squash': typeof SportsSquashRoute
  '/sports/taichi': typeof SportsTaichiRoute
  '/sports/tennis': typeof SportsTennisRoute
  '/sports/yoga': typeof SportsYogaRoute
  '/sports/zumba': typeof SportsZumbaRoute
  '/the-club/careers': typeof TheClubCareersRoute
  '/the-club/committee': typeof TheClubCommitteeRoute
  '/the-club/history': typeof TheClubHistoryRoute
  '/the-club/procurement': typeof TheClubProcurementRoute
  '/the-club/rules': typeof TheClubRulesRoute
  '/dining/': typeof DiningIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/dining/menus/$menu': typeof DiningMenusMenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/venue-hire'
    | '/back-office/login'
    | '/gallery/$album'
    | '/membership/reciprocal'
    | '/sports/bollywood'
    | '/sports/fitness'
    | '/sports/football'
    | '/sports/golf'
    | '/sports/paddle'
    | '/sports/pool'
    | '/sports/squash'
    | '/sports/taichi'
    | '/sports/tennis'
    | '/sports/yoga'
    | '/sports/zumba'
    | '/the-club/careers'
    | '/the-club/committee'
    | '/the-club/history'
    | '/the-club/procurement'
    | '/the-club/rules'
    | '/dining/'
    | '/gallery/'
    | '/membership/'
    | '/sports/'
    | '/dining/menus/$menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/venue-hire'
    | '/back-office/login'
    | '/gallery/$album'
    | '/membership/reciprocal'
    | '/sports/bollywood'
    | '/sports/fitness'
    | '/sports/football'
    | '/sports/golf'
    | '/sports/paddle'
    | '/sports/pool'
    | '/sports/squash'
    | '/sports/taichi'
    | '/sports/tennis'
    | '/sports/yoga'
    | '/sports/zumba'
    | '/the-club/careers'
    | '/the-club/committee'
    | '/the-club/history'
    | '/the-club/procurement'
    | '/the-club/rules'
    | '/dining'
    | '/gallery'
    | '/membership'
    | '/sports'
    | '/dining/menus/$menu'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/venue-hire'
    | '/back-office/login'
    | '/gallery/$album'
    | '/membership/reciprocal'
    | '/sports/bollywood'
    | '/sports/fitness'
    | '/sports/football'
    | '/sports/golf'
    | '/sports/paddle'
    | '/sports/pool'
    | '/sports/squash'
    | '/sports/taichi'
    | '/sports/tennis'
    | '/sports/yoga'
    | '/sports/zumba'
    | '/the-club/careers'
    | '/the-club/committee'
    | '/the-club/history'
    | '/the-club/procurement'
    | '/the-club/rules'
    | '/dining/'
    | '/gallery/'
    | '/membership/'
    | '/sports/'
    | '/dining/menus/$menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenueHireRoute: typeof VenueHireRoute
  BackOfficeLoginRoute: typeof BackOfficeLoginRoute
  GalleryAlbumRoute: typeof GalleryAlbumRoute
  MembershipReciprocalRoute: typeof MembershipReciprocalRoute
  SportsBollywoodRoute: typeof SportsBollywoodRoute
  SportsFitnessRoute: typeof SportsFitnessRoute
  SportsFootballRoute: typeof SportsFootballRoute
  SportsGolfRoute: typeof SportsGolfRoute
  SportsPaddleRoute: typeof SportsPaddleRoute
  SportsPoolRoute: typeof SportsPoolRoute
  SportsSquashRoute: typeof SportsSquashRoute
  SportsTaichiRoute: typeof SportsTaichiRoute
  SportsTennisRoute: typeof SportsTennisRoute
  SportsYogaRoute: typeof SportsYogaRoute
  SportsZumbaRoute: typeof SportsZumbaRoute
  TheClubCareersRoute: typeof TheClubCareersRoute
  TheClubCommitteeRoute: typeof TheClubCommitteeRoute
  TheClubHistoryRoute: typeof TheClubHistoryRoute
  TheClubProcurementRoute: typeof TheClubProcurementRoute
  TheClubRulesRoute: typeof TheClubRulesRoute
  DiningIndexRoute: typeof DiningIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
  SportsIndexRoute: typeof SportsIndexRoute
  DiningMenusMenuRoute: typeof DiningMenusMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venue-hire': {
      id: '/venue-hire'
      path: '/venue-hire'
      fullPath: '/venue-hire'
      preLoaderRoute: typeof VenueHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/': {
      id: '/membership/'
      path: '/membership'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining/': {
      id: '/dining/'
      path: '/dining'
      fullPath: '/dining/'
      preLoaderRoute: typeof DiningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/rules': {
      id: '/the-club/rules'
      path: '/the-club/rules'
      fullPath: '/the-club/rules'
      preLoaderRoute: typeof TheClubRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/procurement': {
      id: '/the-club/procurement'
      path: '/the-club/procurement'
      fullPath: '/the-club/procurement'
      preLoaderRoute: typeof TheClubProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/history': {
      id: '/the-club/history'
      path: '/the-club/history'
      fullPath: '/the-club/history'
      preLoaderRoute: typeof TheClubHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/committee': {
      id: '/the-club/committee'
      path: '/the-club/committee'
      fullPath: '/the-club/committee'
      preLoaderRoute: typeof TheClubCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/careers': {
      id: '/the-club/careers'
      path: '/the-club/careers'
      fullPath: '/the-club/careers'
      preLoaderRoute: typeof TheClubCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/zumba': {
      id: '/sports/zumba'
      path: '/sports/zumba'
      fullPath: '/sports/zumba'
      preLoaderRoute: typeof SportsZumbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/yoga': {
      id: '/sports/yoga'
      path: '/sports/yoga'
      fullPath: '/sports/yoga'
      preLoaderRoute: typeof SportsYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/tennis': {
      id: '/sports/tennis'
      path: '/sports/tennis'
      fullPath: '/sports/tennis'
      preLoaderRoute: typeof SportsTennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/taichi': {
      id: '/sports/taichi'
      path: '/sports/taichi'
      fullPath: '/sports/taichi'
      preLoaderRoute: typeof SportsTaichiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/squash': {
      id: '/sports/squash'
      path: '/sports/squash'
      fullPath: '/sports/squash'
      preLoaderRoute: typeof SportsSquashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/pool': {
      id: '/sports/pool'
      path: '/sports/pool'
      fullPath: '/sports/pool'
      preLoaderRoute: typeof SportsPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/paddle': {
      id: '/sports/paddle'
      path: '/sports/paddle'
      fullPath: '/sports/paddle'
      preLoaderRoute: typeof SportsPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/golf': {
      id: '/sports/golf'
      path: '/sports/golf'
      fullPath: '/sports/golf'
      preLoaderRoute: typeof SportsGolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/football': {
      id: '/sports/football'
      path: '/sports/football'
      fullPath: '/sports/football'
      preLoaderRoute: typeof SportsFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/fitness': {
      id: '/sports/fitness'
      path: '/sports/fitness'
      fullPath: '/sports/fitness'
      preLoaderRoute: typeof SportsFitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/bollywood': {
      id: '/sports/bollywood'
      path: '/sports/bollywood'
      fullPath: '/sports/bollywood'
      preLoaderRoute: typeof SportsBollywoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/reciprocal': {
      id: '/membership/reciprocal'
      path: '/membership/reciprocal'
      fullPath: '/membership/reciprocal'
      preLoaderRoute: typeof MembershipReciprocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$album': {
      id: '/gallery/$album'
      path: '/gallery/$album'
      fullPath: '/gallery/$album'
      preLoaderRoute: typeof GalleryAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-office/login': {
      id: '/back-office/login'
      path: '/back-office/login'
      fullPath: '/back-office/login'
      preLoaderRoute: typeof BackOfficeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining/menus/$menu': {
      id: '/dining/menus/$menu'
      path: '/dining/menus/$menu'
      fullPath: '/dining/menus/$menu'
      preLoaderRoute: typeof DiningMenusMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenueHireRoute: VenueHireRoute,
  BackOfficeLoginRoute: BackOfficeLoginRoute,
  GalleryAlbumRoute: GalleryAlbumRoute,
  MembershipReciprocalRoute: MembershipReciprocalRoute,
  SportsBollywoodRoute: SportsBollywoodRoute,
  SportsFitnessRoute: SportsFitnessRoute,
  SportsFootballRoute: SportsFootballRoute,
  SportsGolfRoute: SportsGolfRoute,
  SportsPaddleRoute: SportsPaddleRoute,
  SportsPoolRoute: SportsPoolRoute,
  SportsSquashRoute: SportsSquashRoute,
  SportsTaichiRoute: SportsTaichiRoute,
  SportsTennisRoute: SportsTennisRoute,
  SportsYogaRoute: SportsYogaRoute,
  SportsZumbaRoute: SportsZumbaRoute,
  TheClubCareersRoute: TheClubCareersRoute,
  TheClubCommitteeRoute: TheClubCommitteeRoute,
  TheClubHistoryRoute: TheClubHistoryRoute,
  TheClubProcurementRoute: TheClubProcurementRoute,
  TheClubRulesRoute: TheClubRulesRoute,
  DiningIndexRoute: DiningIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  MembershipIndexRoute: MembershipIndexRoute,
  SportsIndexRoute: SportsIndexRoute,
  DiningMenusMenuRoute: DiningMenusMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
