/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenueHireRouteImport } from './routes/venue-hire'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as MembershipIndexRouteImport } from './routes/membership.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as TheClubTendersRouteImport } from './routes/the-club.tenders'
import { Route as TheClubRulesRouteImport } from './routes/the-club.rules'
import { Route as TheClubHistoryRouteImport } from './routes/the-club.history'
import { Route as TheClubCommitteeRouteImport } from './routes/the-club.committee'
import { Route as TheClubCareersRouteImport } from './routes/the-club.careers'
import { Route as SportsTennisRouteImport } from './routes/sports.tennis'
import { Route as SportsSquashRouteImport } from './routes/sports.squash'
import { Route as SportsPoolRouteImport } from './routes/sports.pool'
import { Route as SportsGolfRouteImport } from './routes/sports.golf'
import { Route as SportsFitnessRouteImport } from './routes/sports.fitness'
import { Route as MembershipReciprocalRouteImport } from './routes/membership.reciprocal'
import { Route as GalleryAlbumRouteImport } from './routes/gallery.$album'

const VenueHireRoute = VenueHireRouteImport.update({
  id: '/venue-hire',
  path: '/venue-hire',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/membership/',
  path: '/membership/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubTendersRoute = TheClubTendersRouteImport.update({
  id: '/the-club/tenders',
  path: '/the-club/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubRulesRoute = TheClubRulesRouteImport.update({
  id: '/the-club/rules',
  path: '/the-club/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubHistoryRoute = TheClubHistoryRouteImport.update({
  id: '/the-club/history',
  path: '/the-club/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubCommitteeRoute = TheClubCommitteeRouteImport.update({
  id: '/the-club/committee',
  path: '/the-club/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const TheClubCareersRoute = TheClubCareersRouteImport.update({
  id: '/the-club/careers',
  path: '/the-club/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsTennisRoute = SportsTennisRouteImport.update({
  id: '/sports/tennis',
  path: '/sports/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSquashRoute = SportsSquashRouteImport.update({
  id: '/sports/squash',
  path: '/sports/squash',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsPoolRoute = SportsPoolRouteImport.update({
  id: '/sports/pool',
  path: '/sports/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsGolfRoute = SportsGolfRouteImport.update({
  id: '/sports/golf',
  path: '/sports/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsFitnessRoute = SportsFitnessRouteImport.update({
  id: '/sports/fitness',
  path: '/sports/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipReciprocalRoute = MembershipReciprocalRouteImport.update({
  id: '/membership/reciprocal',
  path: '/membership/reciprocal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryAlbumRoute = GalleryAlbumRouteImport.update({
  id: '/gallery/$album',
  path: '/gallery/$album',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue-hire': typeof VenueHireRoute
  '/gallery/$album': typeof GalleryAlbumRoute
  '/membership/reciprocal': typeof MembershipReciprocalRoute
  '/sports/fitness': typeof SportsFitnessRoute
  '/sports/golf': typeof SportsGolfRoute
  '/sports/pool': typeof SportsPoolRoute
  '/sports/squash': typeof SportsSquashRoute
  '/sports/tennis': typeof SportsTennisRoute
  '/the-club/careers': typeof TheClubCareersRoute
  '/the-club/committee': typeof TheClubCommitteeRoute
  '/the-club/history': typeof TheClubHistoryRoute
  '/the-club/rules': typeof TheClubRulesRoute
  '/the-club/tenders': typeof TheClubTendersRoute
  '/gallery/': typeof GalleryIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/sports/': typeof SportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue-hire': typeof VenueHireRoute
  '/gallery/$album': typeof GalleryAlbumRoute
  '/membership/reciprocal': typeof MembershipReciprocalRoute
  '/sports/fitness': typeof SportsFitnessRoute
  '/sports/golf': typeof SportsGolfRoute
  '/sports/pool': typeof SportsPoolRoute
  '/sports/squash': typeof SportsSquashRoute
  '/sports/tennis': typeof SportsTennisRoute
  '/the-club/careers': typeof TheClubCareersRoute
  '/the-club/committee': typeof TheClubCommitteeRoute
  '/the-club/history': typeof TheClubHistoryRoute
  '/the-club/rules': typeof TheClubRulesRoute
  '/the-club/tenders': typeof TheClubTendersRoute
  '/gallery': typeof GalleryIndexRoute
  '/membership': typeof MembershipIndexRoute
  '/sports': typeof SportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venue-hire': typeof VenueHireRoute
  '/gallery/$album': typeof GalleryAlbumRoute
  '/membership/reciprocal': typeof MembershipReciprocalRoute
  '/sports/fitness': typeof SportsFitnessRoute
  '/sports/golf': typeof SportsGolfRoute
  '/sports/pool': typeof SportsPoolRoute
  '/sports/squash': typeof SportsSquashRoute
  '/sports/tennis': typeof SportsTennisRoute
  '/the-club/careers': typeof TheClubCareersRoute
  '/the-club/committee': typeof TheClubCommitteeRoute
  '/the-club/history': typeof TheClubHistoryRoute
  '/the-club/rules': typeof TheClubRulesRoute
  '/the-club/tenders': typeof TheClubTendersRoute
  '/gallery/': typeof GalleryIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/sports/': typeof SportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dining'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/venue-hire'
    | '/gallery/$album'
    | '/membership/reciprocal'
    | '/sports/fitness'
    | '/sports/golf'
    | '/sports/pool'
    | '/sports/squash'
    | '/sports/tennis'
    | '/the-club/careers'
    | '/the-club/committee'
    | '/the-club/history'
    | '/the-club/rules'
    | '/the-club/tenders'
    | '/gallery/'
    | '/membership/'
    | '/sports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dining'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/venue-hire'
    | '/gallery/$album'
    | '/membership/reciprocal'
    | '/sports/fitness'
    | '/sports/golf'
    | '/sports/pool'
    | '/sports/squash'
    | '/sports/tennis'
    | '/the-club/careers'
    | '/the-club/committee'
    | '/the-club/history'
    | '/the-club/rules'
    | '/the-club/tenders'
    | '/gallery'
    | '/membership'
    | '/sports'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dining'
    | '/events'
    | '/news'
    | '/sitemap.xml'
    | '/venue-hire'
    | '/gallery/$album'
    | '/membership/reciprocal'
    | '/sports/fitness'
    | '/sports/golf'
    | '/sports/pool'
    | '/sports/squash'
    | '/sports/tennis'
    | '/the-club/careers'
    | '/the-club/committee'
    | '/the-club/history'
    | '/the-club/rules'
    | '/the-club/tenders'
    | '/gallery/'
    | '/membership/'
    | '/sports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  EventsRoute: typeof EventsRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenueHireRoute: typeof VenueHireRoute
  GalleryAlbumRoute: typeof GalleryAlbumRoute
  MembershipReciprocalRoute: typeof MembershipReciprocalRoute
  SportsFitnessRoute: typeof SportsFitnessRoute
  SportsGolfRoute: typeof SportsGolfRoute
  SportsPoolRoute: typeof SportsPoolRoute
  SportsSquashRoute: typeof SportsSquashRoute
  SportsTennisRoute: typeof SportsTennisRoute
  TheClubCareersRoute: typeof TheClubCareersRoute
  TheClubCommitteeRoute: typeof TheClubCommitteeRoute
  TheClubHistoryRoute: typeof TheClubHistoryRoute
  TheClubRulesRoute: typeof TheClubRulesRoute
  TheClubTendersRoute: typeof TheClubTendersRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
  SportsIndexRoute: typeof SportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venue-hire': {
      id: '/venue-hire'
      path: '/venue-hire'
      fullPath: '/venue-hire'
      preLoaderRoute: typeof VenueHireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/': {
      id: '/membership/'
      path: '/membership'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/tenders': {
      id: '/the-club/tenders'
      path: '/the-club/tenders'
      fullPath: '/the-club/tenders'
      preLoaderRoute: typeof TheClubTendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/rules': {
      id: '/the-club/rules'
      path: '/the-club/rules'
      fullPath: '/the-club/rules'
      preLoaderRoute: typeof TheClubRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/history': {
      id: '/the-club/history'
      path: '/the-club/history'
      fullPath: '/the-club/history'
      preLoaderRoute: typeof TheClubHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/committee': {
      id: '/the-club/committee'
      path: '/the-club/committee'
      fullPath: '/the-club/committee'
      preLoaderRoute: typeof TheClubCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-club/careers': {
      id: '/the-club/careers'
      path: '/the-club/careers'
      fullPath: '/the-club/careers'
      preLoaderRoute: typeof TheClubCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/tennis': {
      id: '/sports/tennis'
      path: '/sports/tennis'
      fullPath: '/sports/tennis'
      preLoaderRoute: typeof SportsTennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/squash': {
      id: '/sports/squash'
      path: '/sports/squash'
      fullPath: '/sports/squash'
      preLoaderRoute: typeof SportsSquashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/pool': {
      id: '/sports/pool'
      path: '/sports/pool'
      fullPath: '/sports/pool'
      preLoaderRoute: typeof SportsPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/golf': {
      id: '/sports/golf'
      path: '/sports/golf'
      fullPath: '/sports/golf'
      preLoaderRoute: typeof SportsGolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/fitness': {
      id: '/sports/fitness'
      path: '/sports/fitness'
      fullPath: '/sports/fitness'
      preLoaderRoute: typeof SportsFitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/reciprocal': {
      id: '/membership/reciprocal'
      path: '/membership/reciprocal'
      fullPath: '/membership/reciprocal'
      preLoaderRoute: typeof MembershipReciprocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$album': {
      id: '/gallery/$album'
      path: '/gallery/$album'
      fullPath: '/gallery/$album'
      preLoaderRoute: typeof GalleryAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  EventsRoute: EventsRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenueHireRoute: VenueHireRoute,
  GalleryAlbumRoute: GalleryAlbumRoute,
  MembershipReciprocalRoute: MembershipReciprocalRoute,
  SportsFitnessRoute: SportsFitnessRoute,
  SportsGolfRoute: SportsGolfRoute,
  SportsPoolRoute: SportsPoolRoute,
  SportsSquashRoute: SportsSquashRoute,
  SportsTennisRoute: SportsTennisRoute,
  TheClubCareersRoute: TheClubCareersRoute,
  TheClubCommitteeRoute: TheClubCommitteeRoute,
  TheClubHistoryRoute: TheClubHistoryRoute,
  TheClubRulesRoute: TheClubRulesRoute,
  TheClubTendersRoute: TheClubTendersRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  MembershipIndexRoute: MembershipIndexRoute,
  SportsIndexRoute: SportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
